- name: Install nginx on mixed os server
  hosts: all servers
  become: yes

  tasks:
    - name: Install nginx on Debian-base system
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install nginx on RedHat-base system
      yum:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == "RedHat"